import { Outfit } from "next/font/google";
import "./globals.css";

// import { ToastContainer } from "react-toastify";
import Navber from "@/components/Navber";
// import Footer from "@/components/Footer";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className={`h-full antialiased`}>
      <body className={`${outfit.className} min-h-full flex flex-col`}>
        <Navber />
        <main className="container mx-auto">{children}</main>
        {/* <Footer /> */}
        {/* <ToastContainer /> */}
      </body>
    </html>
  );
}
